GET http://localhost:8000/api/v1/smartphones

POST http://localhost:8000/api/v1/smartphones
Content-Type: application/json
{
  "title": "Some stupid stuff",
  "description": "lorem ipsum dolor sit amet, consectetur adipiscing el",
  "brand": "Samsung",
  "color": "White",
  "price": "120"
}
