name: Tech API
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Nodejs version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run install:server
      - run: npm run test:api
